config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :students, except: :show

  root 'students#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  belongs_to :user

  validates :first_name, length: { maximum: 40 }, presence: true
  validates :last_name, length: { maximum: 40 }, presence: true
  validates :middle_name, length: { maximum: 60 }
  validates :gender, presence: true
  validates :identifier, length: { minimum: 6, maximum: 16 }, allow_blank: true, uniqueness: true

  GENDERS = %w[male female].freeze

  SORTING = {
    '' => '',
    'Full name (A-Z)' => 'last_name, first_name, middle_name',
    'Full name (Z-A)' => 'last_name desc, first_name desc, middle_name desc',
    'Identifier (A-Z)' => 'identifier',
    'Identifier (Z-A)' => 'identifier desc',
    'Gender (A-Z)' => 'gender',
    'Gender (Z-A)' => 'gender desc'
  }.freeze

  def full_name
    "#{last_name} #{first_name} #{middle_name}".strip
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ApplicationController
  def index
    students = Student.where(user_id: current_user.id)
    @students_count = students.count
    @students = StudentsQuery.new.call(students, params)
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(create_params)

    return redirect_to students_path if @student.save

    render :new
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    return redirect_to students_path if @student.update(update_params)

    render :edit
  end

  def destroy
    @student = Student.find(params[:id])
    @student.delete

    redirect_to students_path
  end

  private

  def create_params
    result = permitted_params.merge(user_id: current_user.id)
    result[:identifier] = nil if result[:identifier] == ''
    result
  end

  def update_params
    result = permitted_params
    result[:identifier] = nil if result[:identifier] == ''
    result
  end

  def permitted_params
    params.require(:student).permit(:first_name, :last_name, :middle_name, :gender, :identifier)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= render 'shared/header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<% if current_user %>
  <nav class='navbar navbar-light bg-light'>
    <a class='navbar-brand'>Students</a>
    <form class='form-inline'>
      <%= current_user.email %> &nbsp;
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    </form>
  </nav>
<% end %>

app/views/students/_form.html.erb
<%= form_with(model: @student, local: true) do |form| %>
  <% if @student && @student.errors.any? %>
    <div class='row'>
      <div class='col mt-3'>
        <div class='alert alert-danger' role='alert'>
          <h2><%= pluralize(@student.errors.count, 'error') %> prohibited this from being saved:</h2>
          <ul>
            <% @student.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>

  <div class='row'>
    <div class='col-lg-4 mb-3'>
      <div class='field form-group'>
        <%= form.label :last_name, class: 'col-form-label' %>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>
    </div>
    <div class='col-lg-4 mb-3'>
      <div class='field form-group'>
        <%= form.label :first_name, class: 'col-form-label' %>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>
    </div>
    <div class='col-lg-4 mb-3'>
      <div class='field form-group'>
        <%= form.label :middle_name, class: 'col-form-label' %>
        <%= form.text_field :middle_name, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='col-lg-2 mb-3'>
      <div class='field form-group'>
        <%= form.label :gender, 'Gender', class: 'col-form-label' %>
        <%= form.select :gender, Student::GENDERS, { include_blank: true }, { class: 'form-control' } %>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='col-lg-4 mb-3'>
      <div class='field form-group'>
        <%= form.label :identifier, class: 'col-form-label' %>
        <%= form.text_field :identifier, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class='action form-group'>
    <%= form.submit class: 'btn btn-success' %>
    <%= link_to 'Cancel', students_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class='row mb-3 mt-3'>
  <div class='col'>
    <%= link_to 'Add student', new_student_path, class: 'btn btn-success' %>
  </div>
  <div class='col'>
    Number of students: <%= @students_count %>
  </div>
</div>

<%= form_with(url: students_path, method: 'GET', local: true, class: 'form-group') do |form| %>
  <div class='row'>
    <div class='col-lg-6'>
      <div class='input-group'>
        <%= form.text_field :filter, class: 'form-control', placeholder: 'Filter...', value: params[:filter] %>
        <span class='mdi mdi-magnify'></span>
        <div class='input-group-append'>
          <%= form.submit 'Filter', class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
    <div class='col-lg-6'>
      <div class='input-group mb-3'>
        <div class='input-group-prepend'>
          <label class='input-group-text'>Sort</label>
        </div>

        <%= form.select :sort, options_for_select(Student::SORTING.keys, params[:sort]),{}, { onchange: "window.location='/students?sort=' + this.value", class: 'custom-select'} %>
      </div>
    </div>
  </div>
<% end %>

<div class='table-responsive'>
  <table class='table table-sm table-centered table-striped dt-responsive nowrap w-100'>
    <thead>
      <tr>
        <th>Full name</th>
        <th>Gender</th>
        <th>Identifier</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= link_to student.full_name, edit_student_path(id: student.id) %></td>
          <td><%= student.gender %></td>
          <td><%= student.identifier %></td>
          <td>
            <%= link_to 'Remove', student_path(student), method: :delete,  data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/new.html.erb
<%= render 'form' %>